version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: /npm
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
